<?php
?>
<h1>About the Project</h1>

Welcome to Rent-a-Flat.

<p>This is sample project created to demonstrate
Zend Framework support in NetBeans IDE. Don't worry to dig into code to
see how it works and how you can make your development easier with Zend and NetBeans!</p>

<p>Let us know what you think on our mailing list <a href="mailto:users@php.netbeans.org">users@php.netbeans.org</a></p>

<p>Let us know if you find any mistake or place for improvement.</p>

<p>The README file can be found <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'readme'), null, true); ?>" target="_blank">here</a>.</p>

